trigger:
  branches:
    include:
      - main

stages:
- stage: BuildStage
  displayName: Build Stage

  jobs:
  - job: MavenBuildJob
    displayName: Maven Build Job

    pool:
      vmImage: ubuntu-latest

    steps:

    - task: Maven@3
      displayName: Build Maven Project

      inputs:
        mavenPomFile: 'artifact1/pom.xml'

        goals: 'clean package'

        mavenOptions: '-Xmx3072m'

        javaHomeOption: 'JDKVersion'

        jdkVersionOption: '17'

        jdkArchitectureOption: 'x64'

        publishJUnitResults: true

        testResultsFiles: '**/surefire-reports/TEST-*.xml'

    - task: PublishBuildArtifacts@1
      displayName: Publish Artifacts

      inputs:
        PathtoPublish: 'artifact1/target'

        ArtifactName: 'drop'

        publishLocation: 'Container'